name: tres_connect
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 5.0.0+289

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  path: ^1.8.3
  flutter_pdfview: ^1.2.7
  flutter_contacts: ^1.1.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  fl_chart: ^0.61.0
  webview_flutter: ^4.0.6
  flutter_inappwebview: 5.7.2+3 #added because webview_flutter does not supports permission handling. Needs more analysis
  floor: ^1.4.1
  dio: ^5.0.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.0.17
  workmanager: ^0.5.1
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^13.0.0
  horizontal_picker: ^1.2.0
  numberpicker: ^2.1.1
  flutter_slidable: ^3.0.0
  path_provider: ^2.0.14
  #Firebase dependencies
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_messaging: ^14.3.0
  firebase_crashlytics: ^3.0.17
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  flutter_otp_text_field: ^1.1.1
  percent_indicator: ^4.2.3
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.10
  screenshot: ^2.1.0
  share_plus: ^7.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter:
    sdk: flutter
  # watch_sdk:
  #   path: ../watch_sdk/
  # mp_chart:
  #   path: ../mp_chart/
  lottie: ^2.3.2
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_animate: ^4.1.1+1
  image_picker: ^0.8.7+4
  file_picker: ^5.2.9
  image_cropper: ^3.0.3
  open_file: ^3.3.1
  camera: ^0.10.5+2
  flutter_screenutil: ^5.8.4
  image: ^4.0.17
  fluttertoast: ^8.2.2
  health: ^7.0.1
  # win32: ^4.0.0
  #health: ^6.0.0
  # health:
  #   git:
  #     url: https://github.com/cachapa/flutter-plugins.git
  #     path: packages/health

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  floor_generator: ^1.4.1
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  flutter_gen_runner:
    # health:
    # path: ../health/

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
